### ISSUE TITLE
authenticate_PAT() function not showing up in package namespace

### ISSUE THREAD

**Issue by benjaminrobinson** [vusaverse/vvtableau#4]
It seems that the `authenticate_PAT` function that shows up in the package documentation website does not exist when I try to use it locally when downloading the most recent version of `vvtableau`.  Just a heads up.  Thanks again for this great package!  Really useful stuff.

**Comment by tin900** [comment]
Hi @benjaminrobinson 

Thanks for bringing this to our attention! We've identified and addressed the issue you reported earlier this week. Please refer to this commit for the changes we've made: 9f83556fe00af449e33411faefb9d187acb51ef4

We've recently updated the package on CRAN. However, due to the time constraints of the CRAN team, we'll hold off on making another update until the beginning of February.

In the meantime, we recommend two alternatives:

- Use the function with three colons to access it:

```
vvtableau:::authenticate_PAT()
```

- Install the development version from GitHub, which should resolve the issue:

```
devtools::install_github("vusaverse/vvtableau")
library(vvtableau)
```
We will keep this issue open until the package has been updated on CRAN.

Please let us know if you encounter any further issues.

**Comment by tin900** [comment]
Hi @benjaminrobinson,

The new version of `vvtableau` has been published to CRAN, therefore I will now close this issue.
